### PR TITLE
stm32 usb cdc

### PR DESCRIPTION
**Pull request by NagaHimanshu**
## Pull Request Description

Modified USB CDC ACM support irrespective of USB_OTG_HS / USB_OTG_FS. 
Updated respective iio demo project supporting SDP-K1.

## PR Type
- [ ] Bug fix (change that fixes an issue)
- [x] New feature (change that adds new functionality)
- [ ] Breaking change (has dependencies in other repos or will cause CI to fail)

## PR Checklist
- [x] I have followed the [Coding style guidelines](http://analogdevicesinc.github.io/no-OS/drivers_guide.html#coding-style)
- [x] I have performed a self-review of the changes
- [x] I have commented my code, at least hard-to-understand parts
- [x] I have build all projects affected by the changes in this PR
- [x] I have tested in hardware affected projects, at the relevant boards
- [x] I have signed off all commits from this PR
- [ ] I have updated the documentation (wiki pages, ReadMe etc), if applies

### CODE REVIEW

**Review by amiclaus — APPROVED** [review]

**Review by buha — CHANGES_REQUESTED** [review]
looks good but i need to test it on both f413zh and k1

(the request changes action is just to disallow merge until i test, no change required)

**Review by buha — APPROVED** [review]
i confirm it works on f413zh board

**Comment by buha** [comment]
there is a CI error but it's not related to this PR so I'll merge

**Pull request merged**
