### PR TITLE
More iio fixes

### PR DESCRIPTION
**Pull request by mchindri**
The result can be seen here:
iio_demo
iio.h and iio_types.h can be opened from here

### CODE REVIEW

**Review by amiclaus — COMMENTED** [review]
Were these changes tested for the no-OS projects?

**Review by adrimbarean — APPROVED** [review]
Looks good to me.

**Comment by mchindri** [comment]
> hese changes tested for the no-OS projects?

Was tested on iio_demo

**Review by amiclaus — APPROVED** [review]
Tested also on fmcdaq2 and the build works fine.

**Pull request merged**
