### PR TITLE
libraries: remove libtinyiiod deps

### PR DESCRIPTION
**Pull request by amiclaus**
The submodule is no longer used.

## Pull Request Description

Please replace this with a detailed description and motivation of the changes. 
You can tick the checkboxes below with an 'x' between square brackets or just check them after publishing the PR. 
If this PR contains a breaking change, list dependent PRs and try to push all related PRs at the same time.

## PR Type
- [ ] Bug fix (change that fixes an issue)
- [ ] New feature (change that adds new functionality)
- [ ] Breaking change (has dependencies in other repos or will cause CI to fail)

## PR Checklist
- [ ] I have followed the [Coding style guidelines](http://analogdevicesinc.github.io/no-OS/drivers_guide.html#coding-style)
- [ ] I have performed a self-review of the changes
- [ ] I have commented my code, at least hard-to-understand parts
- [ ] I have build all projects affected by the changes in this PR
- [ ] I have tested in hardware affected projects, at the relevant boards
- [ ] I have signed off all commits from this PR
- [ ] I have updated the documentation (wiki pages, ReadMe etc), if applies

### CODE REVIEW

**Comment by buha** [comment]
Hmm, so I did another search and here's what I found:
```
[dari@plex no-OS]$ ag -Q "libraries/iio/libtinyiiod"
drivers/Makefile
23:	 -I../libraries/iio/libtinyiiod \

ci/run_build.sh
55:    git submodule update --init libraries/iio/libtinyiiod

tools/scripts/libraries.mk
14:	   -DTINYIIOD_VERSION_GIT=0x$(shell git -C $(NO-OS)/libraries/iio/libtinyiiod/ \
```
First and second results are easy to deal with, lines to be removed.

Third one is trickier but I think all this can be removed too:
```
CFLAGS += -DTINYIIOD_VERSION_MAJOR=0	 \
	   -DTINYIIOD_VERSION_MINOR=1		 \
	   -DTINYIIOD_VERSION_GIT=0x$(shell git -C $(NO-OS)/libraries/iio/libtinyiiod/ \
	   				rev-parse --short HEAD) \
	   -DIIOD_BUFFER_SIZE=0x1000		 \
	   -D_USE_STD_INT_TYPES
```

**Review by amiclaus — COMMENTED** [review]
> Hmm, so I did another search and here's what I found:
> 
> ```
> [dari@plex no-OS]$ ag -Q "libraries/iio/libtinyiiod"
> drivers/Makefile
> 23:	 -I../libraries/iio/libtinyiiod \
> 
> ci/run_build.sh
> 55:    git submodule update --init libraries/iio/libtinyiiod
> 
> tools/scripts/libraries.mk
> 14:	   -DTINYIIOD_VERSION_GIT=0x$(shell git -C $(NO-OS)/libraries/iio/libtinyiiod/ \
> ```
> 
> First and second results are easy to deal with, lines to be removed.
> 
> Third one is trickier but I think all this can be removed too:
> 
> ```
> CFLAGS += -DTINYIIOD_VERSION_MAJOR=0	 \
> 	   -DTINYIIOD_VERSION_MINOR=1		 \
> 	   -DTINYIIOD_VERSION_GIT=0x$(shell git -C $(NO-OS)/libraries/iio/libtinyiiod/ \
> 	   				rev-parse --short HEAD) \
> 	   -DIIOD_BUFFER_SIZE=0x1000		 \
> 	   -D_USE_STD_INT_TYPES
> ```

For the third aspect, we still need to handle the following FLAG:
https://github.com/analogdevicesinc/no-OS/blob/1a29b0c3972a5abdb6afb205bda49b680e3bf2c7/tools/scripts/libraries.mk#L18

Moreover we still have a lot of dependencies on `TINYIIOD` variable in projects `src.mk` and `builds.json`.

**Review by amiclaus — COMMENTED** [review]
sync changes with latest master branch.

**Review by rbolboac — APPROVED** [review]
changes look good to me, build is working so I don't think this breaks anything. wiki documentations might need adaptations until all documentations are ported on GitHub...

**Review by buha — APPROVED** [review]

**Pull request merged**
