### PR TITLE
Bring AD9081 no-OS driver in sync with the Linux version

### PR DESCRIPTION
**Pull request by dbogdan**
Coresponding Linux commits:
 - https://github.com/analogdevicesinc/linux/commit/bc8c8fe66ab2d15d277653c0078ba32d25f7640a
 - https://github.com/analogdevicesinc/linux/commit/a4adec872c8ebd6f40104346369cb3fa75b9e672
 - https://github.com/analogdevicesinc/linux/commit/5b92f26c9d61d13e79d4be64924cb1a47cec39e9
 - https://github.com/analogdevicesinc/linux/commit/8221591d5e3206fd49bdaed1b23b22d1ad37bb66
 - https://github.com/analogdevicesinc/linux/commit/81532e3806f05a4578e8bdb2e7b7e572bf795970

### CODE REVIEW

**Comment by buha** [comment]
I think you should fix the codacy complaint, it looks like a bug with an easy fix, make i a signed integer.

**Comment by buha** [comment]
It's great you provided the corresponding linux commit hashes in the pull request description, but I think it would be super helpful to put it into each commit description too. Useful when browsing git history...

**Comment by dbogdan** [comment]
I wouldn't touch the API - I can however let the dedicated team about the issues.

**Comment by buha** [comment]
Ok, I agree, better fix the bug upstream.

**Pull request merged**
