### PR TITLE
Cn0565 prototype drivers and project

### PR DESCRIPTION
**Pull request by buha**
This is the initial version of the cn0565 project for Body
Impedance Analysis.

The projects currently builds for and runs on aducm3029 and SDP-K1.

make builds a custom application that communicates over UART to a
corresponding libiio app (sw_eit_ad5940).

make TINYIIOD=y builds an app that runs an iiod server. The same
libiio app (sw_eit_ad5940) may be used in iio mode to connect to
the iiod server, but iio-oscilloscope or other iio clients may be
used as well.

### CODE REVIEW

**Review by amiclaus — COMMENTED** [review]
Is ba64392 subject for review? Also, i'd sugest moving `bia_measurement.c` and `bia_measurement.h` under a subfolder so it can be easily intregrated into the CI ignore list :)

Similar to: https://github.com/analogdevicesinc/no-OS/commit/7e248e4b0092e3a11f4d6c24cbd457b56c82a28f

**Review by amiclaus — COMMENTED** [review]
can we add a .json file for the integration in the projects build?

**Comment by buha** [comment]
- added builds.json with builds for both stm32 and aducm3029 platforms

**Review by dbogdan — APPROVED** [review]

**Comment by buha** [comment]
i need to fix the project due to recent changes in gpio_irq on several platforms

**Comment by buha** [comment]
fixed rebase and project, all tests pass, merging

**Pull request merged**
