### PR TITLE
projects: move axi_core drivers & altera platform drivers

### PR DESCRIPTION
**Pull request by amiclaus**
The patch contains the following modifications within no-OS repository:

1. move `altera_platform` drivers from `projects/drivers/` to `/drivers/platform/altera` folder.
2. move axi core drivers from `projects/drivers/` to `/drivers/axi_core` folder.
3. update README files from `/projects/` according to the new file paths for altera platform and axi_core.

Signed-off-by: Antoniu Miclaus <antoniu.miclaus@analog.com>

### CODE REVIEW

**Comment by dbogdan** [comment]
The README updates should be done simultaneously with the changes that make them necessary.

**Comment by amiclaus** [comment]
This PR contains both the drivers migration and the README updates that are dependent.
The PR branch was tested (new paths from README files). Is there something that is missing?

**Comment by dbogdan** [comment]
The changes should be done simultaneously in one commit (not in one pull-request), so if someone will want to do a "git checkout <commit-sha>", will get a working version.

**Comment by amiclaus** [comment]
Got it. Thanks.

**Comment by amiclaus** [comment]
Changelog v1->v2:

- squash commits (updated README files + altera drivers migration + axi drivers migration)

**Pull request merged**
