### PR TITLE
Renamed the header files for the maxim drivers

### PR DESCRIPTION
**Pull request by CiprianRegus**
Renamed all header files specific to the maxim platform drivers to follow the "maxim_peripheral.h" format instead of "peripheral_extra.h". Also updated the projects accordingly.

### CODE REVIEW

**Review by amiclaus — APPROVED** [review]

**Comment by rbolboac** [comment]
Just one question from my side: should the multiple include guards in the header files also be adapted to the new file names?

**Comment by CiprianRegus** [comment]
You're right, I'll update the include guards.

**Review by amiclaus — COMMENTED** [review]
it seems there are some valid build issues for the maxim projects.

**Comment by CiprianRegus** [comment]
- Renamed the header guards.
- Fixed the build issues for projects on maxim.

**Comment by CiprianRegus** [comment]
- Updated the adt7420 project to reflect the renaming.

**Review by amiclaus — APPROVED** [review]

**Pull request merged**
