### PR TITLE
projects: adrv9008-1/adrv9008-2 support

### PR DESCRIPTION
**Pull request by amiclaus**
Add support for ADRV9008-1 and ADRV9008-2.

Signed-off-by: Antoniu Miclaus <antoniu.miclaus@analog.com>

### CODE REVIEW

**Comment by scuciurean** [comment]
Isn't this forcing you to use either tx or rx?
I would use `#ifdef ADRV9008_1`/`#ifdef ADRV9008_1` and for adrv9009 define both as active.

**Review by amiclaus — COMMENTED** [review]
> 
> 
> Isn't this forcing you to use either tx or rx?
> I would use `#ifdef ADRV9008_1`/`#ifdef ADRV9008_2` and for adrv9009 define both as active.

I used #ifndefs so that the defafult configuration remains the same. 

As stated also here:
https://github.com/analogdevicesinc/no-OS/blob/b7c03e86ed8dbf1cb7c276eb933cfe74ac4b746b/projects/adrv9009/src/app/app_config.h#L53-L55

Not changing anything with respect to the defines, will run the application as it is. (for adrv9009)

**Comment by scuciurean** [comment]
> > Isn't this forcing you to use either tx or rx?
> > I would use `#ifdef ADRV9008_1`/`#ifdef ADRV9008_2` and for adrv9009 define both as active.
> 
> I used #ifndefs so that the defafult configuration remains the same.
> 
> As stated also here:
> 
> https://github.com/analogdevicesinc/no-OS/blob/b7c03e86ed8dbf1cb7c276eb933cfe74ac4b746b/projects/adrv9009/src/app/app_config.h#L53-L55
> 
> Not changing anything with respect to the defines, will run the application as it is. (for adrv9009)

Oh, you are right

**Review by scuciurean — APPROVED** [review]

**Comment by dbogdan** [comment]
initCalMask needs to be updated too.

**Comment by amiclaus** [comment]
V2:
- update `initCalMask`

**Review by dbogdan — APPROVED** [review]

**Pull request merged**
