### PR TITLE
adxrs290-pmdz: Add hardware trigger support

### PR DESCRIPTION
**Pull request by rbolboac**
- adxrs290-pmdz project structure re-organization
- adxrs290-pmdz hardware trigger support
- IIO_EXAMPLE for aducm3029, maxim and stm32 platform
- IIO_TRIGGER_EXAMPLE for maxim platform

### CODE REVIEW

**Comment by rbolboac** [comment]
Can be merged only after https://github.com/analogdevicesinc/no-OS/pull/1363 is merged.

**Comment by rbolboac** [comment]
- master rebase

**Review by buha — APPROVED** [review]
looks good, i like that you split the last commit separately, i will use it as a template when adding new platforms

**Review by CiprianRegus — APPROVED** [review]
Looks good.

**Pull request merged**
