### PR TITLE
proojects: ad-acevsecrdset-sl: AddADE9113 rename

### PR DESCRIPTION
**Pull request by danmois**
The ADE9113 is a precision simultaneously sampling Σ-Δ analog-to-digital converter (ADCs) for both DC and polyphase shunt-based energy metering applications. The ADE9113 integrates safety certified signal and power galvanic isolation with three simultaneously sampling fully differential 24-bit Σ-Δ ADC channels. 

## Pull Request Description

Please replace this with a detailed description and motivation of the changes. 
You can tick the checkboxes below with an 'x' between square brackets or just check them after publishing the PR. 
If this PR contains a breaking change, list dependent PRs and try to push all related PRs at the same time.

## PR Type
- [ ] Bug fix (change that fixes an issue)
- [x] New feature (change that adds new functionality)
- [ ] Breaking change (has dependencies in other repos or will cause CI to fail)

## PR Checklist
- [x] I have followed the [Coding style guidelines](http://analogdevicesinc.github.io/no-OS/drivers_guide.html#coding-style)
- [x] I have performed a self-review of the changes
- [x] I have commented my code, at least hard-to-understand parts
- [x] I have build all projects affected by the changes in this PR
- [x] I have tested in hardware affected projects, at the relevant boards
- [x] I have signed off all commits from this PR
- [ ] I have updated the documentation (wiki pages, ReadMe etc), if applies

### CODE REVIEW

**Review by rbolboac — COMMENTED** [review]
are there any functional changes involved here? it looks like there are only renames performed.
anyhow, if there are any functional changes, it would be a good idea to split this commit in 2 commits. first one would be to simply perform the renaming from ade7913 to ade79113, which would not imply any real functional changes. 
then for a second commit add the actual functional changes.
if no functional changes are present then maybe just specify in the commit message that only renaming is performed.

**Comment by danmois** [comment]
> are there any functional changes involved here? it looks like there are only renames performed. anyhow, if there are any functional changes, it would be a good idea to split this commit in 2 commits. first one would be to simply perform the renaming from ade7913 to ade79113, which would not imply any real functional changes. then for a second commit add the actual functional changes. if no functional changes are present then maybe just specify in the commit message that only renaming is performed.

There are no functional changes. Will update commit message.

**Comment by rbolboac** [comment]
> > are there any functional changes involved here? it looks like there are only renames performed. anyhow, if there are any functional changes, it would be a good idea to split this commit in 2 commits. first one would be to simply perform the renaming from ade7913 to ade79113, which would not imply any real functional changes. then for a second commit add the actual functional changes. if no functional changes are present then maybe just specify in the commit message that only renaming is performed.
> 
> There are no functional changes. Will update commit message.

Maybe just state in the commit that a rename is performed. The support is already present so the commit message does not really fit to what the commit is actually doing.

**Comment by danmois** [comment]
V2

- change commit title and message

**Review by rbolboac — APPROVED** [review]
lgtm

**Review by amiclaus — APPROVED** [review]

**Review by buha — APPROVED** [review]

**Pull request merged**
