### PR TITLE
"Small" refactor in iio.c

### PR DESCRIPTION
**Pull request by mchindri**
- Remove iio_register and use init param. No project use register during runtime. This simplify a lot structures in desc and xml is generated only once.
 - Some naming changes.

### CODE REVIEW

**Comment by mchindri** [comment]
v2:
 - Fix cppcheck

**Comment by buha** [comment]
So I looked at all commits and agree with all changes.
There is just a slight problem of how the code is split into commits I think, for example:
 - Commit no 5 does "Rename iio_interface -> iio_dev_priv" but I see already iio_dev_priv in commit no 2
 - This whole thing about commenting lines in commit no 2 in functions to be removed in commit no 3 doesn't look good, I think you should just merge 2 & 3
 - Also commit 2 does a bit more than what it says

**Comment by mchindri** [comment]
> So I looked at all commits and agree with all changes. There is just a slight problem of how the code is split into commits I think, for example:
> 
> * Commit no 5 does "Rename iio_interface -> iio_dev_priv" but I see already iio_dev_priv in commit no 2
> * This whole thing about commenting lines in commit no 2 in functions to be removed in commit no 3 doesn't look good, I think you should just merge 2 & 3
> * Also commit 2 does a bit more than what it says

I didn't like how the diff of 2 and 3 together was looking that's why I did it this way. I will try it again.
Will do the suggestions soon.

**Comment by mchindri** [comment]
v3:
 - Do a better split of commit 2 and 3
 - move wrong renaming to correct commit

**Review by buha — APPROVED** [review]

**Review by amiclaus — COMMENTED** [review]
Was this PR tested with at least one no-OS project that has IIO_SUPPORT?

**Comment by mchindri** [comment]
> Was this PR tested with at least one no-OS project that has IIO_SUPPORT?

Yes, ad9361

**Pull request merged**
