### PR TITLE
ci: documentation: update to suggestive namings

### PR DESCRIPTION
**Pull request by amiclaus**
## Pull Request Description

Now that the sphinx build was added to the documentation build, the scripts/function naming should reflect that. For example the doxygen.sh script does now contain more that doxygen builds. Use a more generic name.

## PR Type
- [ ] Bug fix (change that fixes an issue)
- [ ] New feature (change that adds new functionality)
- [ ] Breaking change (has dependencies in other repos or will cause CI to fail)

## PR Checklist
- [x] I have followed the [Coding style guidelines](http://analogdevicesinc.github.io/no-OS/drivers_guide.html#coding-style)
- [x] I have performed a self-review of the changes
- [x] I have commented my code, at least hard-to-understand parts
- [ ] I have build all projects affected by the changes in this PR
- [ ] I have tested in hardware affected projects, at the relevant boards
- [x] I have signed off all commits from this PR
- [ ] I have updated the documentation (wiki pages, ReadMe etc), if applies

### CODE REVIEW

**Comment by SRaus** [comment]
Please move "Now that the sphinx build was added ...." description in PR Description section and remove the comment from there.

**Review by amiclaus — COMMENTED** [review]
> Please move "Now that the sphinx build was added ...." description in PR Description section and remove the comment from there.

The PR description was auto-populated by default with the commit description. Can we handle automatically such that it is populated by default under the PR Description header?

**Comment by SRaus** [comment]
I will do do some research to check if this is possible. 
Thanks for the feedback.

**Review by amiclaus — COMMENTED** [review]
v2:
- change name of the build from `doxygen` to `documentation`

**Review by SRaus — APPROVED** [review]

**Pull request merged**
