### PR TITLE
adrv9002 fixes

### PR DESCRIPTION
**Pull request by dbogdan**

### CODE REVIEW

**Review by amiclaus — APPROVED** [review]
lgtm, besides some minor change required by the code style constraints.

**Review by adrimbarean — APPROVED** [review]
Looks good to me. I think it would be good to merge the 8th and 7th commits together, since commit 7 reverts some of the changes done in commit 4 and commit 8 redoes them.

**Comment by dbogdan** [comment]
v2:
 - split axi_adc/dac_init() to axi_adc/dac_init_begin() and axi_adc/dac_init_finish()

**Comment by dbogdan** [comment]
v3:
 - merge the two "drivers: adrv9002: Do not directly access the physical memory" commits

**Comment by dbogdan** [comment]
v4:
 - fix astyle complaints

**Pull request merged**
