### PR TITLE
projects: remove platform drivers header 

### PR DESCRIPTION
**Pull request by amiclaus**
Remove `platform_drivers.h` header file from projects.

Use header files available in `/include` folder instead.

Signed-off-by: Antoniu Miclaus <antoniu.miclaus@analog.com>

### CODE REVIEW

**Comment by amiclaus** [comment]
Changelog v1->v2:

- fix code style issues.

**Comment by amiclaus** [comment]
Changelog v1->v2:

- fix code style issues.
- perform rebase.

**Comment by mirceacaprioru** [comment]
you have some conflicts here, please fix them before merge.

**Comment by amiclaus** [comment]
Changelog v2->v3:

- resolve conflicts

**Comment by mirceacaprioru** [comment]
there still are conflicts here.

**Comment by amiclaus** [comment]
The conflicts appeared with the merge of the latest PR. Should be fixed now.

**Pull request merged**
