### PR TITLE
prerequisites for no-OS networking

### PR DESCRIPTION
**Pull request by buha**
no-OS networking is work in progress but meanwhile, these changes will be needed to make it happen.

### CODE REVIEW

**Review by amiclaus — COMMENTED** [review]
Are `projects/iio_demo/sample_sine.dat` and` projects/iio_demo/sample_ramp.dat` changes related to the PR/commit topic?

**Comment by rbolboac** [comment]
> Are `projects/iio_demo/sample_sine.dat` and` projects/iio_demo/sample_ramp.dat` changes related to the PR/commit topic?

@buha , I would actually keep those files, because they are useful when testing iio_demo project.

**Comment by buha** [comment]
@rbolboac @amiclaus deleting those files was a mistake, will put them back

**Comment by buha** [comment]
v2:
- reverted .dat files removal

**Review by rbolboac — APPROVED** [review]

**Review by amiclaus — APPROVED** [review]

**Review by CiprianRegus — APPROVED** [review]
Besides the 247d8e11 and 826535a8 being too long, it looks good.

**Pull request merged**
