### PR TITLE
adrv9371 rework

### PR DESCRIPTION
**Pull request by dbogdan**

### CODE REVIEW

**Comment by commodo** [comment]
@amiclaus   the atyle script needs tuning ; it shoudn't try to format deleted files

**Comment by amiclaus** [comment]
@commodo fixed with #127

**Comment by commodo** [comment]
oh right;
let's rebase this branch and see what happens

**Comment by commodo** [comment]
Changelog v1 -> v2:
* rebased on top of newer master

**Comment by commodo** [comment]
Will merge next week if no objections

**Pull request merged**
