### PR TITLE
projects: drop CFLAGS explicit initialization

### PR DESCRIPTION
**Pull request by amiclaus**
Most of the CFLAGS from no-OS projects are used within the code by checking if they are defined. Therefore explicit initialization is redundant. Drop it.

## Pull Request Description

Please replace this with a detailed description and motivation of the changes. 
You can tick the checkboxes below with an 'x' between square brackets or just check them after publishing the PR. 
If this PR contains a breaking change, list dependent PRs and try to push all related PRs at the same time.

## PR Type
- [ ] Bug fix (change that fixes an issue)
- [ ] New feature (change that adds new functionality)
- [ ] Breaking change (has dependencies in other repos or will cause CI to fail)

## PR Checklist
- [x] I have followed the [Coding style guidelines](http://analogdevicesinc.github.io/no-OS/drivers_guide.html#coding-style)
- [x] I have performed a self-review of the changes
- [ ] I have commented my code, at least hard-to-understand parts
- [ ] I have build all projects affected by the changes in this PR
- [ ] I have tested in hardware affected projects, at the relevant boards
- [x] I have signed off all commits from this PR
- [ ] I have updated the documentation (wiki pages, ReadMe etc), if applies

### CODE REVIEW

**Review by amiclaus — COMMENTED** [review]
build issue seems to be unrelated.

**Review by amiclaus — COMMENTED** [review]
v2:
- perform rebase to remove unrelated build issues.

**Review by amiclaus — COMMENTED** [review]
converting this to "ready for review"

**Review by buha — APPROVED** [review]

**Comment by buha** [comment]
We really should work on something like EXAMPLE=basic or EXAMPLE=iio etc. in the future because examples are mutually exclusive and currently we have a lot of crazy stuff like this in-code: https://github.com/analogdevicesinc/no-OS/blob/main/projects/eval-adxl355-pmdz/src/platform/aducm3029/main.c#L115-L120

**Review by dbogdan — APPROVED** [review]

**Pull request merged**
