### PR TITLE
AD9528 - driver rework

### PR DESCRIPTION
**Pull request by buha**
This pull request does the following things:
- update `drivers/frequency/ad9528` with new features such as clk_set_rate, clk_round_rate, hard reset to be able to be more dynamic about ad9628 configuration
- using the above change, make ad9528 completely independent from `profiles/..../talise_config_ad9528.c`
- adapt the application to use the `drivers/frequency/ad9528` driver
- remove the now obsolete `projects/adrv9009/src/devices/ad9528` driver

### CODE REVIEW

**Comment by dbogdan** [comment]
First of all, please do a rebase for avoiding the conflicts.

**Comment by buha** [comment]
Previous force-pushes contain a rebase on master and some codacy/astyle fixes.

**Comment by scuciurean** [comment]
Please add a description and the signature to every commit.

**Comment by buha** [comment]
Previous force-push updated the commit message description and signature as pointed out:

> Please add a description and the signature to every commit.

**Comment by buha** [comment]
For further reference, here's the execution output on Xilinx ZC706 with ADRV9009-W/PCBZ:

profiles/tx_bw400_ir491p52_rx_bw200_or245p76_orx_bw400_or491p52_dc245p76
```
Hello
rx_clkgen: MMCM-PLL locked (245760000 Hz)
tx_clkgen: MMCM-PLL locked (245760000 Hz)
rx_os_clkgen: MMCM-PLL locked (245760000 Hz)
rx_adxcvr: OK (9830400 kHz)
tx_adxcvr: OK (9830400 kHz)
rx_os_adxcvr: OK (9830400 kHz)
talise: Device Revision 192, Firmware 6.0.2, API 3.6.0.5
talise: Calibrations completed successfully
rx_jesd: Lane 0 desynced (13 errors), restarting link
rx_jesd: Lane 1 desynced (8 errors), restarting link
rx_os_jesd: Lane 0 desynced (65 errors), restarting link
rx_os_jesd: Lane 1 desynced (6 errors), restarting link
rx_jesd status:
	Link is enabled
	Measured Link Clock: 245.779 MHz
	Reported Link Clock: 245.760 MHz
	Lane rate: 9830.400 MHz
	Lane rate / 40: 245.760 MHz
	Link status: DATA
	SYSREF captured: Yes
	SYSREF alignment error: No
tx_jesd status:
	Link is enabled
	Measured Link Clock: 245.779 MHz
	Reported Link Clock: 245.760 MHz
	Lane rate: 9830.400 MHz
	Lane rate / 40: 245.760 MHz
	SYNC~: deasserted
	Link status: DATA
	SYSREF captured: Yes
	SYSREF alignment error: No
rx_os_jesd status:
	Link is enabled
	Measured Link Clock: 245.779 MHz
	Reported Link Clock: 245.760 MHz
	Lane rate: 9830.400 MHz
	Lane rate / 40: 245.760 MHz
	Link status: DATA
	SYSREF captured: Yes
	SYSREF alignment error: No
tx_dac: Successfully initialized (491558837 Hz)
rx_adc: Successfully initialized (245779418 Hz)
Bye
```

profiles/tx_bw200_ir245p76_rx_bw200_or245p76_orx_bw200_or245p76_dc245p76
```
Hello
rx_clkgen: MMCM-PLL locked (245760000 Hz)
tx_clkgen: MMCM-PLL locked (122880000 Hz)
rx_os_clkgen: MMCM-PLL locked (122880000 Hz)
rx_adxcvr: OK (9830400 kHz)
tx_adxcvr: OK (4915200 kHz)
rx_os_adxcvr: OK (4915200 kHz)
talise: Device Revision 192, Firmware 6.0.2, API 3.6.0.5
talise: Calibrations completed successfully
rx_jesd: Lane 0 desynced (17 errors), restarting link
rx_jesd: Lane 1 desynced (7 errors), restarting link
rx_os_jesd: Lane 0 desynced (18 errors), restarting link
rx_os_jesd: Lane 1 desynced (36 errors), restarting link
rx_jesd status:
	Link is enabled
	Measured Link Clock: 245.779 MHz
	Reported Link Clock: 245.760 MHz
	Lane rate: 9830.400 MHz
	Lane rate / 40: 245.760 MHz
	Link status: DATA
	SYSREF captured: Yes
	SYSREF alignment error: No
tx_jesd status:
	Link is enabled
	Measured Link Clock: 122.890 MHz
	Reported Link Clock: 122.880 MHz
	Lane rate: 4915.200 MHz
	Lane rate / 40: 122.880 MHz
	SYNC~: deasserted
	Link status: DATA
	SYSREF captured: Yes
	SYSREF alignment error: No
rx_os_jesd status:
	Link is enabled
	Measured Link Clock: 122.888 MHz
	Reported Link Clock: 122.880 MHz
	Lane rate: 4915.200 MHz
	Lane rate / 40: 122.880 MHz
	Link status: DATA
	SYSREF captured: Yes
	SYSREF alignment error: No
tx_dac: Successfully initialized (245779418 Hz)
rx_adc: Successfully initialized (245779418 Hz)
Bye
```

profiles/tx_bw100_ir122p88_rx_bw100_or122p88_orx_bw100_or122p88_dc122p88
```
Hello
rx_clkgen: MMCM-PLL locked (122880000 Hz)
tx_clkgen: MMCM-PLL locked (61440000 Hz)
rx_os_clkgen: MMCM-PLL locked (61440000 Hz)
rx_adxcvr: OK (4915200 kHz)
tx_adxcvr: OK (2457600 kHz)
rx_os_adxcvr: OK (2457600 kHz)
talise: Device Revision 192, Firmware 6.0.2, API 3.6.0.5
talise: Calibrations completed successfully
rx_jesd: Lane 0 desynced (35 errors), restarting link
rx_jesd: Lane 1 desynced (41 errors), restarting link
rx_os_jesd: Lane 0 desynced (14 errors), restarting link
rx_os_jesd: Lane 1 desynced (9 errors), restarting link
rx_jesd status:
	Link is enabled
	Measured Link Clock: 122.890 MHz
	Reported Link Clock: 122.880 MHz
	Lane rate: 4915.200 MHz
	Lane rate / 40: 122.880 MHz
	Link status: DATA
	SYSREF captured: Yes
	SYSREF alignment error: No
tx_jesd status:
	Link is enabled
	Measured Link Clock: 61.444 MHz
	Reported Link Clock: 61.440 MHz
	Lane rate: 2457.600 MHz
	Lane rate / 40: 61.440 MHz
	SYNC~: deasserted
	Link status: DATA
	SYSREF captured: Yes
	SYSREF alignment error: No
rx_os_jesd status:
	Link is enabled
	Measured Link Clock: 61.444 MHz
	Reported Link Clock: 61.440 MHz
	Lane rate: 2457.600 MHz
	Lane rate / 40: 61.440 MHz
	Link status: DATA
	SYSREF captured: Yes
	SYSREF alignment error: No
tx_dac: Successfully initialized (122891235 Hz)
rx_adc: Successfully initialized (122889709 Hz)
Bye
```

**Comment by buha** [comment]
Previous force-push updated doxygen documentation for the added ad9528 driver functions.

**Pull request merged**
