### PR TITLE
Create AD5460

### PR DESCRIPTION
**Pull request by akilamarimuthu**
## Pull Request Description

Creating Firmware Examples folder AD5460 project.

### CODE REVIEW

**Comment by CiprianRegus** [comment]
Hi,

If you want to add a new project, you should also add the sources in the same commit in which you create the directory. There is already a PR opened for the AD5460 here: https://github.com/analogdevicesinc/no-OS/pull/2147

**Comment by akilamarimuthu** [comment]
Hi,
  Ok. I discussed with Miclaus now.  Will continue with  #2147<https://urldefense.com/v3/__https:/github.com/analogdevicesinc/no-OS/pull/2147__;!!A3Ni8CS0y2Y!6cXLVsO9I1cILDDUJp7w9TqJWAyas_Iiz6F6VfWRptTtLr7L_yV2v3_i5l5F6_att8G19Bmq9QxIRZabYDydujv1TqMJ$>,
   Kindly cancel the PR that I created.

Regards,
Akila

**Review by amiclaus — COMMENTED** [review]
Hi, If you want to add new examples on top of ad5460 I'd suggest waiting for https://github.com/analogdevicesinc/no-OS/pull/2147 to be merged. In the meantime you can use the https://github.com/analogdevicesinc/no-OS/tree/staging/ad5460 branch to create you own branch and add your example there for testing purposes.

**Comment by akilamarimuthu** [comment]
Hi @amiclaus ,
       Got it. I will do as you say.

**Pull request closed without merging**
