### PR TITLE
drivers:platform:maxim:max32670: Add i2c platform driver

### PR DESCRIPTION
**Pull request by jsanbuen**
i2c platform driver for max32670. Tested using MAX32670EVKIT + MAX20361EVKIT for device id 0, 1, and 2 at MAX_I2C_STD_MODE only.

### CODE REVIEW

**Review by buha — APPROVED** [review]

**Comment by buha** [comment]
Actually, there is currently a PR with a fix fir Maxim's I2C implementations, please look at it and change this code accordingly, you can see the explanation in the commit message.
https://github.com/analogdevicesinc/no-OS/pull/1834/commits/88ace84b78dd75fa44b0b91056576281147469cd

**Review by amiclaus — APPROVED** [review]

**Review by buha — CHANGES_REQUESTED** [review]
see my comment above

**Comment by jsanbuen** [comment]
changelog:
-referred to mentioned PR on maxim i2c fix and made necessary changes. 
-tested using max32670evkit + max20335evkit. working for all available device id at STD_MODE I2C speed.

**Review by buha — APPROVED** [review]
looks good now, merging

**Pull request merged**
