### PR TITLE
irq_platform_ops : adding platform ops to irq files

### PR DESCRIPTION
**Pull request by APorumb**
irq_platform_ops : Modified IRQ to support specific platform operations.

Tested with a simple example.

### CODE REVIEW

**Comment by mchindri** [comment]
Why is this needed?

**Review by amiclaus — COMMENTED** [review]
Please make sure that all no-OS projects that use irq interface are working properly.

**Review by dbogdan — APPROVED** [review]

**Review by buha — APPROVED** [review]
looks good, projects build now, only thing would be to check one or two projects (like iio_demo on aducm3029 and on xilinx) and see if they behave normally

if irq doesn't work, uart doesn't work and the project test will fail
if project test is ok then it means irq works too

**Comment by dbogdan** [comment]
@APorumb , when you think the pull request it's ready to be merged, please remove the draft flag.

**Comment by APorumb** [comment]
Tested iio_demo on both xilinx (my side) and aducm3025 (@adrimbarean 's side).

Because xilinx_irq.c has 9 functions and aducm3025_irq.c has only 8 functions (trigger_level_set not supported on aducm3029),
I added a null pointer check at line 127 in drivers/irq/irq.c.

Ready to merge!

**Review by adrimbarean — APPROVED** [review]
Looks good to me.

**Pull request merged**
