### PR TITLE
projects:adrv9001: Use iio_app

### PR DESCRIPTION
**Pull request by mchindri**
Update to use iio_app and refactor a little to simplify the defines.
Not tested

### CODE REVIEW

**Comment by mchindri** [comment]
v2
 - Fix astyle

**Review by amiclaus — APPROVED** [review]
lgtm, as long as this patch was/is tested.

**Review by buha — APPROVED** [review]
same comment as @amiclaus, looks good, needs a test on hardware

**Comment by buha** [comment]
I think 2b47764ff71206baaae9ec8dc54a457f597edc1e might be fishy because I can't get this to run properly.
In debugger it fails here https://github.com/analogdevicesinc/no-OS/blob/master/iio/iio_app/iio_app.c#L267 because somewhere within that function it's checking for the PS/PL type and it's value is junk (https://github.com/analogdevicesinc/no-OS/blob/master/iio/iio_app/iio_app.c#L252)

I also think this variable is not needed https://github.com/analogdevicesinc/no-OS/blob/master/iio/iio_app/iio_app.c#L255

So perhaps have a look at that function, do a test on whatever xilinx PS platform / project you have on hand, and when it works let me know to retest.

**Comment by mchindri** [comment]
v2:
 - rebase onto latest master fix

**Review by amiclaus — COMMENTED** [review]
Some conflicts have appeared in the meantime.

**Comment by mchindri** [comment]
v3: 
 - Rebase onto master

**Pull request merged**
