### PR TITLE
Update all projects with iio_app

### PR DESCRIPTION
**Pull request by mchindri**

### CODE REVIEW

**Review by amiclaus — COMMENTED** [review]
Were these updates tested for each project?

**Comment by mchindri** [comment]
> Were these updates tested for each project?

No. For the moment I want to do the modification on all and have them building. Will see later about testing.

**Comment by mchindri** [comment]
v2:
 - Fix build. no build file for ad9172 for the moment ...

**Comment by mchindri** [comment]
v3: 
 - remove ad9172 because it was added to an other PR
 - fix astyle

**Comment by mchindri** [comment]
v3
 - Add remaining projects

**Comment by mchindri** [comment]
v5 
 - Fix astyle

**Review by amiclaus — APPROVED** [review]
lgtm, as long as we test the changes.

**Comment by mchindri** [comment]
v2:
 - rebase onto latest master fix

**Review by buha — CHANGES_REQUESTED** [review]
This has the same symptom that I mentioned in #1143 - tested on fmcdaq2 on your branch with the latest fix from master applied.
iio_app seems broken.
Since both fmcdaq2 nor adrv9001 projects fail in the same spot, clearly iio_app wasn't tested on xilinx, so please fix iio_app and then we'll test the rest of the projects.

**Comment by buha** [comment]
fmcdaq2 is working in the end, it was likely a false positive in my local environment

**Comment by mchindri** [comment]
fmcdaq3 tested and working too

**Comment by mchindri** [comment]
v3: rebase and fix conflicts

**Comment by mchindri** [comment]
v4:
 - Remove tested projects (moved to #1161 )

**Comment by mchindri** [comment]
v5:
 - Move ad9434 and ad9739 to other PR
 - Tested fmcadc2 (weird signal)

**Comment by mchindri** [comment]
v6:
 - Fix conflicts

**Review by buha — APPROVED** [review]

**Pull request merged**
