### PR TITLE
iio_demo: Add support for new trigger structure

### PR DESCRIPTION
**Pull request by rbolboac**
- Adapt iio_demo driver and iio_demo project for new trigger structure.
- Remove IIO_TRIGGER_EXAMPLE support for platforms which support only UART communication for IIO App.
- Minor code refactoring

### CODE REVIEW

**Comment by rbolboac** [comment]
- master rebase

**Review by amiclaus — APPROVED** [review]

**Comment by rbolboac** [comment]
- removed redundant header from parameters.c in each platform

**Comment by rbolboac** [comment]
- removed local files added by mistake

**Review by adrimbarean — APPROVED** [review]
Looks good to me.

**Pull request merged**
