### PR TITLE
Create libraries.mk

### PR DESCRIPTION
**Pull request by mchindri**
All related to libraries was moved to libraries.mk

Only last commit is relevant.

### CODE REVIEW

**Review by amiclaus — COMMENTED** [review]
Nitpick:
 `tools:scripts: Fix build errors` the commit message should comply the 50/72 format rule.

**Comment by mchindri** [comment]
> Nitpick:
> `tools:scripts: Fix build errors` the commit message should comply the 50/72 format rule.

Only last commit is relevant for this PR, and it fits the 50/72 rule

**Comment by amiclaus** [comment]
> 
> 
> > Nitpick:
> > `tools:scripts: Fix build errors` the commit message should comply the 50/72 format rule.
> 
> Only last commit is relevant for this PR, and it fits the 50/72 rule

But all the commits will be merged to the master branch, right?

**Comment by mchindri** [comment]
> > > Nitpick:
> > > `tools:scripts: Fix build errors` the commit message should comply the 50/72 format rule.
> > 
> > 
> > Only last commit is relevant for this PR, and it fits the 50/72 rule
> 
> But all the commits will be merged to the master branch, right?
 I will rebase onto master when #784 is merged. I fixed the commit there

**Comment by amiclaus** [comment]
> 
> 
> > > > Nitpick:
> > > > `tools:scripts: Fix build errors` the commit message should comply the 50/72 format rule.
> > > 
> > > 
> > > Only last commit is relevant for this PR, and it fits the 50/72 rule
> > 
> > 
> > But all the commits will be merged to the master branch, right?
> > I will rebase onto master when #784 is merged. I fixed the commit there

Got it. Thanks!

**Review by dbogdan — APPROVED** [review]

**Comment by mchindri** [comment]
v2:
 - rebase onto master
 - Split in multiple commits

**Pull request merged**
