### PR TITLE
projects:eval-adxl355-pmdz: Project folder structure re-organization

### PR DESCRIPTION
**Pull request by rbolboac**
Re-organized src structure as follows:
```
├── common
│   ├── common_data.c
│   └── common_data.h
├── examples
│   ├── dummy
│   │   ├── dummy_example.c
│   │   └── dummy_example.h
│   ├── examples_src.mk
│   └── iio_example
│       ├── iio_example.c
│       └── iio_example.h
└── platform
    ├── platform_includes.h
    └── stm32
        ├── main.c
        ├── parameters.c
        ├── parameters.h
        └── platform_src.mk
```

This re-organization will make it easier to add new platform support or to add new examples in the future.

Overview of the new structure:
Common folder:
- contains common initialization data used by examples
- the data is platform independent

Example folder:
- contains folders with examples
- contains makefile which includes the needed files based on the selected examples
- all examples are platform independent

Platform folder:
- contains folders with platforms
- contains makefile which includes the needed files based on the selected platform
- contains main file which runs the selected example routines

### CODE REVIEW

**Comment by rbolboac** [comment]
Fixed astyle and doxygen.

**Review by amiclaus — COMMENTED** [review]
One question on my side: does this re-organization fit with our current build process for the projects? If so, can you please add also the json file?

**Comment by rbolboac** [comment]
@amiclaus , this project is currently using only stm32 platform which is not available at the moment on the build server.

**Review by amiclaus — COMMENTED** [review]
> One question on my side: does this re-organization fit with our current build process for the projects? If so, can you please add also the json file?

got it. thanks.

**Review by adrimbarean — APPROVED** [review]
Looks good to me.

**Review by amiclaus — COMMENTED** [review]
lgtm on this particular project. But we need to decide if we want to use this structure for all no-OS projects. If so, all of them should be updated.

**Review by amiclaus — APPROVED** [review]

**Pull request merged**
