### PR TITLE
projects:ad9361:src:main.c IRQ example fix

### PR DESCRIPTION
**Pull request by danmois**
Specify correct callbacks for tx_dmac and rx_dmac.

Signed-off-by: George Mois <george.mois@analog.com>

### CODE REVIEW

**Review by amiclaus — APPROVED** [review]
lgtm, one minor aspect: for the last two commits either change the commit title since it is identical, either squash them.

**Comment by danmois** [comment]
V2
- rename commits
- add commit for replacing legacy_callback with callback member of no_os_callback_desc

**Review by buha — APPROVED** [review]

**Comment by danmois** [comment]
V3
- remove duplicate commit
- IRQ example does not work correctly on Zynq targets (e.g. ZC706) - faulty xparameters.h

**Comment by danmois** [comment]
V4
- specify correct values for DMA IRQs on ZYNQ targets

**Comment by danmois** [comment]
V5
- place values for DMA IRQs on ZYNQ targets in parameters.h

**Review by amiclaus — APPROVED** [review]

**Pull request merged**
