### PR TITLE
drivers: dac: max22017 : Change driver name to max22017

### PR DESCRIPTION
**Pull request by RaduSabau1**
## Pull Request Description
Old driver name was max2201x, and now it has to be changed to max22017 since it will only support
the specific chip.

## PR Type
- [x] Bug fix (change that fixes an issue)
- [ ] New feature (change that adds new functionality)
- [ ] Breaking change (has dependencies in other repos or will cause CI to fail)

## PR Checklist
- [x] I have followed the [Coding style guidelines](http://analogdevicesinc.github.io/no-OS/drivers_guide.html#coding-style)
- [x] I have performed a self-review of the changes
- [x] I have commented my code, at least hard-to-understand parts
- [x] I have build all projects affected by the changes in this PR
- [x] I have tested in hardware affected projects, at the relevant boards
- [x] I have signed off all commits from this PR
- [x] I have updated the documentation (wiki pages, ReadMe etc), if applies

### CODE REVIEW

**Comment by RaduSabau1** [comment]
V2:
- Fix broken dependencies

**Comment by buha** [comment]
Screenshot from 2024-10-11 15-25-47

Why do the .h files don't show up as `oldfile -> newfile` ? also, the changes count is different (282 vs 289) so this commit does more than it says in the description.

I recommend using `git mv` command to rename files (or rename + move to a different directory)

**Comment by buha** [comment]
Also, I don't see it necessary to have so many commits for this, I'd make 1 commit that renames everything. I find it easier when browsing git log to see only 1 rename commit instead of 5.

**Comment by RaduSabau1** [comment]
Regarding the difference in code lines, that appears because I have removed the enum with the chip IDs, should I mention this in the commit body. Also should all the commits be squashed then?

**Comment by RaduSabau1** [comment]
V3:
- Squashed all commits

**Review by amiclaus — APPROVED** [review]

**Comment by buha** [comment]
```$ ag 2201X
drivers/adc/ad405x/README.rst
70:MAX2201X Driver Initialization Example
```

There is another occurrence in another device driver documentation. Could you please fix that too in a separate commit ?

**Comment by buha** [comment]
actually i'll merge and do it myself in the github editor

**Pull request merged**
