### PR TITLE
drivers:dac:ad5686: fix driver

### PR DESCRIPTION
**Pull request by amiclaus**
1. Replace undefined macros for i2c stop bit.

2. Fix gpio init param types.

Signed-off-by: Antoniu Miclaus <antoniu.miclaus@analog.com>

### CODE REVIEW

**Comment by dbogdan** [comment]
2 unrelated changes in 1 commit.

**Comment by amiclaus** [comment]
There are 2 fixes in the same driver. One without another still makes the driver broken.

**Comment by mirceacaprioru** [comment]
I also think this should go in 2 commits. Even if the first one does not fix the driver alone it fixes the part it is referring to.

**Comment by amiclaus** [comment]
v2:
- split into 2 commits

**Pull request merged**
