### PR TITLE
projects: fmcdaq3 initial version

### PR DESCRIPTION
**Pull request by amiclaus**
Update FMCDAQ3 project to use latest platform drivers and AXI core implementations.
Folder structure is kept similar to the updated projects.
Add makefile support for FMCDAQ2 project (Makefile, src.mk).

Signed-off-by: Antoniu Miclaus antoniu.miclaus@analog.com

### CODE REVIEW

**Comment by amiclaus** [comment]
V2: 
- remove old folder from root when performing the project move.

**Comment by dbogdan** [comment]
Was this tested on both Xilinx and Intel platforms?

**Comment by amiclaus** [comment]
V3:

- update all ad9528 parameters to the latest changes of the driver.

**Comment by amiclaus** [comment]
> 
> 
> Was this tested on both Xilinx and Intel platforms?

It was tested on both Xilinx and Intel platforms. For Intel platform there is still an issue with the rx link (the status is CGS).

**Pull request merged**
