### PR TITLE
Doxygen Integration

### PR DESCRIPTION
**Pull request by amiclaus**
Add Doxygen to no-OS repository.

Integrate Doxygen into TravisCI to auto-generate documentation for latest version of `master` branch.

Signed-off-by: Antoniu Miclaus <antoniu.miclaus@analog.com>

### CODE REVIEW

**Comment by amiclaus** [comment]
V2:

- Minor indent adjustment for CMakeLists

**Comment by amiclaus** [comment]
I will merge it later if no objections.

**Comment by cseci** [comment]
V3: 

- change encrypted value

**Comment by amiclaus** [comment]
V3:

- change encrypted value

**Comment by amiclaus** [comment]
V4:
- Use different Doxygen version 1.8.13
- Fix Doxygen `warning/error` catch on Travis builds

**Comment by amiclaus** [comment]
V5:
Use XML input file to customize the layout of the Doxygen pages.

1. Hide Class/File Members tab
2. Hide Modules tab
3. Rename Classes->Structures

**Comment by amiclaus** [comment]
V6:
- update Doxygen to newer version 1.8.17. This version implements a feature that will be used: links between doxygen pages and documented files/folders.

**Pull request merged**
