### PR TITLE
build_projects.yml: change group variable for next_stable

### PR DESCRIPTION
**Pull request by AAndrisa**
## Pull Request Description

A new group of variables was created in azure just for next_stable branch and now we point to that one.

## PR Type
- [ ] Bug fix (change that fixes an issue)
- [ ] New feature (change that adds new functionality)
- [x] Breaking change (has dependencies in other repos or will cause CI to fail)

## PR Checklist
- [x] I have followed the [Coding style guidelines](http://analogdevicesinc.github.io/no-OS/drivers_guide.html#coding-style)
- [x] I have performed a self-review of the changes
- [ ] I have commented my code, at least hard-to-understand parts
- [ ] I have build all projects affected by the changes in this PR
- [ ] I have tested in hardware affected projects, at the relevant boards
- [x] I have signed off all commits from this PR
- [ ] I have updated the documentation (wiki pages, ReadMe etc), if applies

### CODE REVIEW

**Comment by SRaus** [comment]
On line 324-25, you have: 
  _```
- name: branch
    value: $(Build.SourceBranchName)
```_
Couldn't you use 'branch' variable instead of hardcoding it, since thre is 'next_stable' in both - No-OS and HDL ?

**Comment by AAndrisa** [comment]
> On line 324-25, you have: _```
> 
> * name: branch
>   value: $(Build.SourceBranchName)
> 
> ```
> Couldn't you use 'branch' variable instead of hardcoding it, since thre is 'next_stable' in both - No-OS and HDL ?
> ```

In this case I can, but it won't work for release branches, so if you consider the variable `branch` from line 25 is a better fit, I can change it.

**Comment by AAndrisa** [comment]
v2: updated PR description and name because the way we set the variable HDL_BRANCH was changed using a new group of variables just for next_stable branch.

**Review by amiclaus — APPROVED** [review]
this looks better now :)

**Review by SRaus — APPROVED** [review]

**Pull request merged**
