### PR TITLE
drivers: ad411x: rename ad4111_regs.h file to ad411x_regs.h

### PR DESCRIPTION
**Pull request by adrimbarean**
The AD4111 and AD4112 devices have the register structure identical,
with the exception of one bit in the GPIOCON register. Rename the
register file to include the whole family not just AD4111.

Signed-off-by: Andrei Drimbarean <Andrei.Drimbarean@analog.com>

### CODE REVIEW

**Comment by commodo** [comment]
I'm vague here.
Why rename the file to a non-standard filename ?

**Comment by adrimbarean** [comment]
I was thinking the file is intended to be used with both AD4111 and AD 4112 and to not create confiusion because it is named only ad4111_regs.h

**Comment by amiclaus** [comment]
Retrigger PR

**Comment by commodo** [comment]
[LGTM](https://i.pinimg.com/564x/6d/7e/cb/6d7ecb7b20cd01db5e78f16281703021.jpg)

**Comment by commodo** [comment]
astyle has some complaints

**Pull request merged**
