### PR TITLE
drivers: ad5686: ad5686.c: Fix Header comment

### PR DESCRIPTION
**Pull request by amiclaus**
Fix header comment for set Power-down mode function.

Signed-off-by: Antoniu Miclaus <antoniu.miclaus@analog.com>

### CODE REVIEW

**Comment by commodo** [comment]
[LGTM](https://i0.wp.com/www.metdaan.com/wp-content/uploads/2018/02/Screenshot_5-9.png)

**Comment by commodo** [comment]
[curios] Is this ready for merge or will there be more changes and wait a bit more ?

**Comment by amiclaus** [comment]
It's ready for merge from my side

**Comment by commodo** [comment]
Ok.

Will merge this later today if no objections

**Pull request merged**
