### PR TITLE
8 - iio small changes

### PR DESCRIPTION
**Pull request by mchindri**
I couldn't reopen #702 

Here are the commit from #702 and some iio fixes

### CODE REVIEW

**Comment by mchindri** [comment]
v2:
 - Apply astyle

**Comment by mchindri** [comment]
v3: 
 - Keep just 2 commits in this PR . Will create other PR for the remaining commits

**Comment by amiclaus** [comment]
Is there a solid reason why you removed 3 commits from here and add a new PR(#710) ? (Which currently contains 3 commits)

Do you plan to add more commits in the last PR (#710)?

As it is now, 5 commits should be fine in one PR.

**Comment by mchindri** [comment]
> Is there a solid reason why you removed 3 commits from here and add a new PR(#710) ? (Which currently contains 3 commits)
> 
> Do you plan to add more commits in the last PR (#710)?
> 
> As it is now, 5 commits should be fine in one PR.

There were 12 commit here. Commits on #710 can be merged by itself. Remaining commits removed from here will go in a new PR. If there are few commits in a PR I think it can be merged faster

**Pull request merged**
