### PR TITLE
ad7768-1fmcz: ad77681: ad7761 noos library update

### PR DESCRIPTION
**Pull request by jgarlitos**

### CODE REVIEW

**Comment by amiclaus** [comment]
Hello, for the code style issues that were detected by Travis CI build you can use the following guide to fix them: https://github.com/analogdevicesinc/no-OS/wiki/Code-Style-guidelines

**Comment by amiclaus** [comment]
Please make sure that the commit titles do not exceed the maximum admitted length, otherwise the text will be truncated and splited into title and description.

Besides the title, a commit description would be nice, mentioning with details the changes/updates made.

**Comment by jgarlitos** [comment]
Done running Astyle.

**Comment by scuciurean** [comment]
If all the astyle issues are caused by the previous commits, you could squash the "Run Astyle" commit.
The rest looks good to me.

**Comment by cristiantpop** [comment]
Looks good to me, just remove last commit and run astyle, on the other commits.

**Comment by jgarlitos** [comment]
Hi All,
Done fixing the code style error and squashing the 3rd and 4th commits.

**Pull request merged**
